source_stream_name = "prod_sales_events"
output_stream_name = "prod_sales_predictions"
model_bucket = "prod-mlartifact-s3"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "prod_stream_model_stores_sales-prediction"
lambda_function_name = "prod_prediction_lambda"
