source_stream_name = "stg_sales_events"
output_stream_name = "stg_sales_predictions"
model_bucket = "stg-mlartifact-s3"
lambda_function_local_path = "../lambda_function.py"
docker_image_local_path = "../Dockerfile"
ecr_repo_name = "stg_stream_model_stores_sales-prediction"
lambda_function_name = "stg_prediction_lambda"
