channels:
- conda-forge
dependencies:
- python=3.9.0
- pip<=23.3.2
- pip:
  - mlflow==2.22.0
  - cloudpickle==3.1.1
  - numpy==1.23.5
  - psutil==5.9.8
  - scikit-learn==1.0.2
  - scipy==1.10.1
name: mlflow-env
